package edu.drexel.psal.anonymouth.engine;

/**
 * Contains all features known to Anonymouth. By having a standardized set of feature names, reflection may be confidently used to call suggestors and calculators
 * @author Andrew W.E. McDonald
 *
 */
public enum FeatureList {
	
	FLESCH_READING_EASE_SCORE, LETTER_SPACE, AVERAGE_SYLLABLES_IN_WORD, CHARACTER_SPACE,
	GUNNING_FOG_READABILITY_INDEX, AVERAGE_SENTENCE_LENGTH, SENTENCE_COUNT, COMPLEXITY, UNIQUE_WORDS_COUNT, LETTER_N_GRAMS,
	FUNCTION_WORDS, LETTERS_PERCENTAGE, CHARACTER_COUNT, MISSPELLED_WORDS, WORD_TRIGRAMS, WORD_BIGRAMS, WORDS,
	POS_TRIGRAMS, POS_BIGRAMS, POS_TAGS, PUNCTUATION, WORD_LENGTHS, THREE_DIGIT_NUMBERS, TWO_DIGIT_NUMBERS, DIGITS, UPPERCASE_LETTERS_PERCENTAGE,
	TOP_LETTER_TRIGRAMS, DIGITS_PERCENTAGE, TOP_LETTER_BIGRAMS, LETTERS, AVERAGE_CHARACTERS_PER_WORD, SPECIAL_CHARACTERS
	
}
